import { EntityStore } from "./entitystore";
import { Source } from "./source";
export declare class Entity {
    private _entityStore;
    protected _properties: any;
    private _name;
    private _key;
    private _ref;
    private _isReferenced;
    private _source;
    private _isItem;
    private _isCollection;
    protected _item: any;
    constructor(entityStore: EntityStore, name: string, ref?: Entity, item?: any);
    set key(value: string);
    get key(): string;
    get name(): string;
    get ref(): Entity | undefined;
    get properties(): any;
    get source(): Source;
    get entityStore(): EntityStore;
    set source(source: Source);
    get isReferenced(): boolean;
    set isItem(value: boolean);
    get isItem(): boolean;
    delete(): void;
    get(index: number): any;
    add(): Entity;
    remove(index: number): void;
    serialize(): any;
    deserialize(entity: any): void;
}
